server:
  port: 80803

datasource:
    url: jdbc:mysql://localhost:3306/empleado-service
    username: root
    password: 

# JPA settings

jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
